"use client";

import { useState } from "react";
import { Sparkles, CheckCircle2, ArrowRight } from "lucide-react";
import { cyberAudio } from "@/lib/cyberAudio";

export default function AiInsightBrief() {
  const [isExecuting, setIsExecuting] = useState<string | null>(null);
  const [actionDone, setActionDone] = useState<string | null>(null);

  const handleAction = (actionId: string, actionName: string) => {
    cyberAudio.play("warp");
    setIsExecuting(actionId);
    setActionDone(null);

    setTimeout(() => {
      setIsExecuting(null);
      setActionDone(actionName);
      cyberAudio.play("chime");
      setTimeout(() => setActionDone(null), 3000);
    }, 1200);
  };

  return (
    <div className="cyber-card p-4 sm:p-5 flex flex-col gap-3.5 select-none font-mono relative overflow-hidden border border-[#BF40FF]/25 shadow-[0_0_20px_rgba(191,64,255,0.1)]">
      <div className="flex flex-wrap items-center justify-between gap-2 pb-2.5 border-b border-white/10">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-lg bg-[#BF40FF]/20 border border-[#BF40FF]/40 flex items-center justify-center">
            <Sparkles size={15} className="text-[#BF40FF]" />
          </div>
          <div className="flex flex-col">
            <h3 className="text-xs font-black text-[#F1F3F9] tracking-wider uppercase">
              TACTICAL AI BRIEFING // <span className="text-[#BF40FF]">NEURAL COGNITION</span>
            </h3>
            <span className="text-[10px] text-[#9499B3]">Generated by DeepMind Gemini 2.5 Flash Agent</span>
          </div>
        </div>

        <span className="text-[10px] font-bold text-[#00FF41] px-2 py-0.5 rounded bg-[#00FF41]/10 border border-[#00FF41]/30 flex items-center gap-1">
          <span className="w-1.5 h-1.5 rounded-full bg-[#00FF41] animate-pulse" />
          SYSTEM NOMINAL
        </span>
      </div>

      {/* AI Synthesized Intelligence Report */}
      <div className="p-3.5 rounded-xl bg-black/40 border border-white/5 flex flex-col gap-2 text-xs">
        <p className="text-[#F1F3F9] leading-relaxed font-sans text-xs sm:text-[13px]">
          &ldquo;Cluster telemetry indicates zero critical anomalies in the past 24 hours. Prompt caching is currently saving{" "}
          <span className="font-bold text-[#00FF41] font-mono">~$18.40/day</span> in inference compute. PostgreSQL vector indexes are healthy with a{" "}
          <span className="font-bold text-[#00F0FF] font-mono">68.4%</span> cache hit ratio. 3 GitHub pull requests are verified and passing all unit tests.&rdquo;
        </p>

        <div className="flex flex-wrap items-center gap-2 pt-2 border-t border-white/5 text-[10px]">
          <span className="px-2 py-0.5 rounded bg-[#00FF41]/10 text-[#00FF41] border border-[#00FF41]/20 font-bold">
            ✓ 14/14 Microservices Healthy
          </span>
          <span className="px-2 py-0.5 rounded bg-[#00F0FF]/10 text-[#00F0FF] border border-[#00F0FF]/20 font-bold">
            ✓ 0 Zero-Day Vulnerabilities
          </span>
          <span className="px-2 py-0.5 rounded bg-[#BF40FF]/10 text-[#BF40FF] border border-[#BF40FF]/20 font-bold">
            ✓ Swarm Load: Balanced (64% CPU)
          </span>
        </div>
      </div>

      {/* Recommended Quick Tactical Actions */}
      <div className="flex flex-col gap-1.5 pt-1">
        <span className="text-[10px] text-[#4F536E] uppercase font-bold tracking-wider">
          Suggested Autonomous Actions:
        </span>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 text-xs">
          <button
            onClick={() => handleAction("cache", "Context cache compacted & pruned")}
            disabled={isExecuting !== null}
            className="p-2 rounded-xl bg-white/[0.03] border border-white/10 hover:border-[#00FF41]/40 hover:bg-[#00FF41]/10 text-[#9499B3] hover:text-[#00FF41] transition-all flex items-center justify-between text-left cursor-pointer disabled:opacity-50"
          >
            <div className="flex flex-col">
              <span className="font-bold text-[11px] text-[#F1F3F9]">Prune Vector Cache</span>
              <span className="text-[9px] text-[#4F536E]">Reclaim ~240MB RAM</span>
            </div>
            <ArrowRight size={12} />
          </button>

          <button
            onClick={() => handleAction("probe", "Synthetic mesh probes executed")}
            disabled={isExecuting !== null}
            className="p-2 rounded-xl bg-white/[0.03] border border-white/10 hover:border-[#00F0FF]/40 hover:bg-[#00F0FF]/10 text-[#9499B3] hover:text-[#00F0FF] transition-all flex items-center justify-between text-left cursor-pointer disabled:opacity-50"
          >
            <div className="flex flex-col">
              <span className="font-bold text-[11px] text-[#F1F3F9]">Global Health Probe</span>
              <span className="text-[9px] text-[#4F536E]">Ping 5 edge regions</span>
            </div>
            <ArrowRight size={12} />
          </button>

          <button
            onClick={() => handleAction("agent", "Hermes Agent dispatched to deep scan")}
            disabled={isExecuting !== null}
            className="p-2 rounded-xl bg-white/[0.03] border border-white/10 hover:border-[#BF40FF]/40 hover:bg-[#BF40FF]/10 text-[#9499B3] hover:text-[#BF40FF] transition-all flex items-center justify-between text-left cursor-pointer disabled:opacity-50"
          >
            <div className="flex flex-col">
              <span className="font-bold text-[11px] text-[#F1F3F9]">Dispatch Hermes Scan</span>
              <span className="text-[9px] text-[#4F536E]">Audit new CVE advisories</span>
            </div>
            <ArrowRight size={12} />
          </button>
        </div>

        {actionDone && (
          <div className="mt-1 p-2 rounded-lg bg-[#00FF41]/10 border border-[#00FF41]/30 text-xs text-[#00FF41] flex items-center gap-2 animate-fade-in">
            <CheckCircle2 size={13} />
            <span>{actionDone}</span>
          </div>
        )}
      </div>
    </div>
  );
}
